apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk   # base64("rootpassword")
  MYSQL_PASSWORD: c2VjcmV0cGFzcw==       # base64("secretpass")
