# docker compose up --build

version: "3.9"
services:
  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    container_name: repl_master
    environment:
      - REPLICATE_TIMEOUT_SEC=60
    ports:
      - "5000:5000"
    networks:
      - repl_net

  secondary:
    build:
      context: .
      dockerfile: Dockerfile.secondary
    environment:
      - MASTER_URL=http://master:5000
    networks:
      - repl_net
    ports:
      - "5001:5001"
    depends_on:
      - master

  secondary_slow:
    build:
      context: .
      dockerfile: Dockerfile.secondary
    environment:
      - MASTER_URL=http://master:5000
      - SECONDARY_DELAYS=10
    networks:
      - repl_net
    ports:
      - "5002:5001"
    depends_on:
      - master

networks:
  repl_net:
    driver: bridge
